name: MLOps CI/CD Pipeline

on:
  push:
    branches: [ "main" ]


jobs:
  mlops:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do cÃ³digo
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Instalar depÃªndencias
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validar dados
        run: python src/validate_data.py

      - name: Executar testes
        run: pytest
      
      - name: Treinar modelo
        run: python src/train.py

      - name: Avaliar modelo
        run: python src/evaluate.py

      - name: ðŸ“¦ Publicar artefatos
        uses: actions/upload-artifact@v4
        with:
          name: modelo-treinado
          path: |
            model.joblib
            metrics.json
